/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Send } from './Send';
export * as factories from './factories';
export { Send__factory } from './factories/Send__factory';
